name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: ["trigger-event"]
  schedule:
    - cron: 0 0 * * *

jobs:
  build_and_test:
    runs-on: macos-11
    steps:
    - name: xcode switch
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '13.0'
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Earendil  
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
