name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build_and_test_macos11_xcode13:
    name: Build and test all  platforms (runs on BigSur and xcode13)
    runs-on: macos-11
    steps:
    - name: xcode switch
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '13.0'
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Earendil  
    - name: Build and test ( macOS 12.0 Monterey)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( mac Catalyst 12.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 mini'
    - name: Build and test ( tvOS 15.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=tvOS Simulator,OS=15.0,name=Apple TV 4K (2nd generation)'
    - name: Build and test ( watchOS 8.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=watchOS Simulator,OS=8.0,name=Apple Watch Series 6 - 40mm'
