name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build_and_test_xcode13:
    name: Build and test all  platforms (xcode 13)
    runs-on: macos-11
    steps:
    - name: xcode switch
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '13.0'
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Earendil  
    - name: Build and test ( macOS 12.0 Monterey)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( mac Catalyst 12.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( tvOS 15.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=tvOS Simulator,OS=15.0,name=Apple TV 4K (2nd generation)'
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'
    - name: Build and test ( watchOS 8.0)
      run: xcodebuild test -scheme Earendil -destination 'platform=watchOS Simulator,OS=8.0,name=Apple Watch Series 6 - 40mm'
  build_and_test_xcode12_5_1:
    name: Build and test all  platforms (xcode 12.5.1)
    runs-on: macos-11
    steps:
    - name: xcode switch
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '12.5.1'
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Earendil  
    - name: Build and test ( macOS 11.3)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( mac Catalyst 11.3)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( tvOS 14.5)
      run: xcodebuild test -scheme Earendil -destination 'platform=tvOS Simulator,OS=14.5,name=Apple TV 4K (2nd generation)'
    - name: Build and test ( iOS 14.5)
      run: xcodebuild test -scheme Earendil -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro Max'
    - name: Build and test ( watchOS 7.4)
      run: xcodebuild test -scheme Earendil -destination 'platform=watchOS Simulator,OS=7.4,name=Apple Watch Series 6 - 40mm'
  build_and_test_xcode11_7:
    name: Build and test all  platforms (xcode 11.7)
    runs-on: macos-11
    steps:
    - name: xcode switch
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: '11.7'
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme Earendil  
    - name: Build and test ( macOS 10.15)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( mac Catalyst 10.15)
      run: xcodebuild test -scheme Earendil -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( tvOS 13.4)
      run: xcodebuild test -scheme Earendil -destination 'platform=tvOS Simulator,OS=13.4,name=Apple TV 4K'
    - name: Build and test ( iOS 13.7)
      run: xcodebuild test -scheme Earendil -destination 'platform=iOS Simulator,OS=13.4,name=iPhone 8'
    - name: Build and test ( watchOS 6.2)
      run: xcodebuild test -scheme Earendil -destination 'platform=watchOS Simulator,OS=6.2,name=Apple Watch Series 4 - 44mm'
